/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteRouteImport } from './routes/post/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as PostCreateRouteImport } from './routes/post/create'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAccountRouteImport } from './routes/(auth)/account'
import { Route as PostIdRouteRouteImport } from './routes/post/$id/route'
import { Route as PostIdIndexRouteImport } from './routes/post/$id/index'
import { Route as PostIdEditRouteImport } from './routes/post/$id/edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PostRouteRoute = PostRouteRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostRouteRoute,
} as any)
const PostCreateRoute = PostCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PostRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAccountRoute = authAccountRouteImport.update({
  id: '/(auth)/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRouteRoute = PostIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostRouteRoute,
} as any)
const PostIdIndexRoute = PostIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostIdRouteRoute,
} as any)
const PostIdEditRoute = PostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post': typeof PostRouteRouteWithChildren
  '/post/$id': typeof PostIdRouteRouteWithChildren
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/post/create': typeof PostCreateRoute
  '/post/': typeof PostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/post/$id/edit': typeof PostIdEditRoute
  '/post/$id/': typeof PostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/post/create': typeof PostCreateRoute
  '/post': typeof PostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/post/$id/edit': typeof PostIdEditRoute
  '/post/$id': typeof PostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/post': typeof PostRouteRouteWithChildren
  '/post/$id': typeof PostIdRouteRouteWithChildren
  '/(auth)/account': typeof authAccountRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/post/create': typeof PostCreateRoute
  '/post/': typeof PostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/post/$id/edit': typeof PostIdEditRoute
  '/post/$id/': typeof PostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/post'
    | '/post/$id'
    | '/account'
    | '/login'
    | '/register'
    | '/post/create'
    | '/post/'
    | '/api/auth/$'
    | '/post/$id/edit'
    | '/post/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/post/create'
    | '/post'
    | '/api/auth/$'
    | '/post/$id/edit'
    | '/post/$id'
  id:
    | '__root__'
    | '/'
    | '/post'
    | '/post/$id'
    | '/(auth)/account'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/post/create'
    | '/post/'
    | '/api/auth/$'
    | '/post/$id/edit'
    | '/post/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostRouteRoute: typeof PostRouteRouteWithChildren
  authAccountRoute: typeof authAccountRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/post/create': {
      id: '/post/create'
      path: '/create'
      fullPath: '/post/create'
      preLoaderRoute: typeof PostCreateRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/account': {
      id: '/(auth)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/post/$id/': {
      id: '/post/$id/'
      path: '/'
      fullPath: '/post/$id/'
      preLoaderRoute: typeof PostIdIndexRouteImport
      parentRoute: typeof PostIdRouteRoute
    }
    '/post/$id/edit': {
      id: '/post/$id/edit'
      path: '/edit'
      fullPath: '/post/$id/edit'
      preLoaderRoute: typeof PostIdEditRouteImport
      parentRoute: typeof PostIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PostIdRouteRouteChildren {
  PostIdEditRoute: typeof PostIdEditRoute
  PostIdIndexRoute: typeof PostIdIndexRoute
}

const PostIdRouteRouteChildren: PostIdRouteRouteChildren = {
  PostIdEditRoute: PostIdEditRoute,
  PostIdIndexRoute: PostIdIndexRoute,
}

const PostIdRouteRouteWithChildren = PostIdRouteRoute._addFileChildren(
  PostIdRouteRouteChildren,
)

interface PostRouteRouteChildren {
  PostIdRouteRoute: typeof PostIdRouteRouteWithChildren
  PostCreateRoute: typeof PostCreateRoute
  PostIndexRoute: typeof PostIndexRoute
}

const PostRouteRouteChildren: PostRouteRouteChildren = {
  PostIdRouteRoute: PostIdRouteRouteWithChildren,
  PostCreateRoute: PostCreateRoute,
  PostIndexRoute: PostIndexRoute,
}

const PostRouteRouteWithChildren = PostRouteRoute._addFileChildren(
  PostRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostRouteRoute: PostRouteRouteWithChildren,
  authAccountRoute: authAccountRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
